apiVersion: v1
kind: Secret
metadata:
  name: go-auth-api-secret
  labels:
    app: go-auth-api
type: Opaque
data:
  # These are base64 encoded values
  # You should generate your own with: echo -n "your-value" | base64
  DB_PASSWORD: cG9zdGdyZXM=  # "postgres" in base64
  JWT_SECRET: Y2hhbmdlLXRoaXMtdG8tYS1zdHJvbmctc2VjcmV0LWtleQ==  # "change-this-to-a-strong-secret-key" in base64