// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/PakornBank/go-backend-example/internal/auth (interfaces: Handler)
//
// Generated by this command:
//
//	mockgen -destination=./handler_mock.go -package=auth github.com/PakornBank/go-backend-example/internal/auth Handler
//

// Package auth is a generated GoMock package.
package auth

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockHandler) Login(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Login", c)
}

// Login indicates an expected call of Login.
func (mr *MockHandlerMockRecorder) Login(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockHandler)(nil).Login), c)
}

// Register mocks base method.
func (m *MockHandler) Register(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", c)
}

// Register indicates an expected call of Register.
func (mr *MockHandlerMockRecorder) Register(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockHandler)(nil).Register), c)
}
